ilkkderss/ilkkderss/Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace ilkkderss.Models
{
    public class Customer
    {
        //public int CustomerId { get; set; }

        //Validationda yani doğrulamada kullanacağım zorunluluklarımı burada girdim


        [Required(ErrorMessage ="isim kısmını boş geçemezsiniz")]
        [StringLength(30,ErrorMessage ="max 30 karakter kullanabilirsin!")]
        public string CustomerName { get; set; }

        public string CustomerSurname { get; set; }

        [EmailAddress(ErrorMessage ="Emailinizi kontrol ediniz")]
        public string Email { get; set; }



    }
}

ilkkderss/ilkkderss/Models/ErrorViewModel.cs
using System;

namespace ilkkderss.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ilkkderss/ilkkderss/Models/Product.cs
namespace ilkkderss.Models
{
    public class Product
    {
       public int Id { get; set; }

        public string ProductName { get; set; }

        public int ProductPrice { get; set; }   



    }
}

ilkkderss/ilkkderss/Controllers/CustomerController.cs
using ilkkderss.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ilkkderss.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult MusteriDogrulama()
        {

            return View();

        }


        [HttpPost]
        public IActionResult MusteriDogrulama(Customer model)
        {

            if(!ModelState.IsValid)
            {

                ViewBag.HataMesaj = ModelState.Values.FirstOrDefault(x => x.ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid).Errors[0].ErrorMessage;


            }



           return View(model); 

        }
    }
}

ilkkderss/ilkkderss/Controllers/HomeController.cs
using ilkkderss.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ilkkderss.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ilkkderss/ilkkderss/Controllers/ProductController.cs
using ilkkderss.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ilkkderss.Controllers
{
    public class ProductController : Controller
    {
        //ACTION TURLERI DONUS TIPLERI

        /*
       
         Bildiğiniz üzere clientten gelen requestleri controlerımız karsılayıp
        uygun actiona yonlendırmekteydı...
         Actionda ihtiyacımıza göre operasyonu yönetiyordu
         İşte bu durumlarda metodumuzun farklı türleri olabilmekte....
         
         
         */

        //JSON TİPİ DONÜŞ
        #region JsonResult
        public JsonResult GetProducts()
        {


            JsonResult result = Json(new Product

            {
                Id= 1,
                ProductName ="IPHONE",
                ProductPrice = 150


            });
            
            
            
            
            return result;

        }
        #endregion

        //ACTİOIN RESULT TİPİ DÖNÜŞ VE VERİ LİSTELEME(VİEWBAG,DATA ETC)
        public IActionResult Index()
        {

            var products = new List<Product>
            {


                new Product { Id= 1, ProductName ="SAMSUNG",ProductPrice =160},
                new Product { Id= 2, ProductName ="VESTEL",ProductPrice=120},
                new Product { Id= 3, ProductName ="NOKİA",ProductPrice=150}


            };


        

            #region VİEWBAG

            //Taşınacak olan veriyi dinamik bir şekilde almamızı sağlayan yapıdır(değişkenle)

            ViewBag.products = products;

            #endregion

            #region ViEWDATA
            //Bu yapıda viewbag gibi veri taşımamıza yarar.Ancak farklı olarak boxing ve unboxing işlemleri vardır


            ViewData["products"]=products;  



            #endregion




            return View();
        }


        /*EKRANA SAYFAYI TAŞIYAN DEFAULTUNDA GET OLAN ALTTAKI ACTİONIM*/
        public IActionResult CreateProduct()
        { 
            return View();
        
        }
        /*BU YAPI İSE KULLANICIDAN PARAMETRELERLE VERİLERİ KARŞILADI*/
        [HttpPost]
        public IActionResult CreateProduct(string txtName,string txtProductPrice)
        {
            return View();

        }

    }
}

ilkkderss/ilkkderss/Views/Customer/MusteriDogrulama.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers

@model ilkkderss.Models.Customer

@*Controller tarafında tanımladıgımız viewbagi burada karşılıyorum...*@
@ViewBag.HataMesaj


<form asp-action="MusteriDogrulama" asp-controller="Customer" method="post">

     
<style>
    #box {
        
        text-align: center;
       
    }
</style>
   
     <div id="box"> 

    <input type="text" name="CustomerName" placeholder="Name" />

    </br>

    <input type="text" name="CustomerSurname" placeholder="Surname" />

    </br> 
    
    
    <input type="email" name="Email" placeholder="Email" />

    </br>


    </br>

    <button >ADD CUSTOMER</button>

     </div>
</form>

ilkkderss/ilkkderss/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ilkkderss/ilkkderss/Views/Product/CreateProduct.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers


<form asp-action="CreateProduct" asp-controller="Product" method="post">

     
<style>
    #box {
        
        text-align: center;
       
    }
</style>
   
     <div id="box"> 

    <input type="text" name="txtName" placeholder="Name" />

    </br>

    <input type="text" name="txtProductPrice" placeholder="Price" />

    </br> </br>

    <button >ADD PRODUCT</button>

     </div>
</form>

ilkkderss/ilkkderss/Views/Product/GetProducts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@




@{


}

ilkkderss/ilkkderss/Views/Product/Index.cshtml
@model List<ilkkderss.Models.Product>


    <h3>VİEW BAGLE NESNE GÖNDERİMİ</h3>
    <ul>

    @*DİNAMİK OLARAK VERİLERİMİ TAŞIYORUM*@

    @foreach (var product in ViewBag.products as List<ilkkderss.Models.Product> )
    {
        <li>

            @product.ProductName


        </li>


        
    }


                
    
    </ul>

     <h3>VİEW DATA KULLANIMI</h3>
    <ul>

    @*OBJECTS OLARAK GETİRİP UNBOXİNG YAPTIM*@

    @foreach (var product in ViewData["products"] as List<ilkkderss.Models.Product> )
    {
        <li>

            @product.ProductName


        </li>


        
    }


                
    
    </ul>

ilkkderss/ilkkderss/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ilkkderss</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ilkkderss</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ilkkderss - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>